/**
 * @file layout.js
 * @brief Define la estructura raíz y los metadatos compartidos del frontend.
 */

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/** Metadatos base utilizados por Next.js para construir el documento HTML. */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Envuelve todas las páginas con las fuentes y estilos globales de la aplicación.
 *
 * Recibe como contenido el árbol React correspondiente a la ruta activa.
 *
 * @returns {JSX.Element} documento raíz de la aplicación
 */
export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
