apiVersion: v1
kind: Secret
metadata:
  name: playhub-secrets
  labels:
    app.kubernetes.io/name: playhub
type: Opaque
stringData:
  DB_PASSWORD: "mi_password"
  JWT_SECRET: "ChangeThisPlayHubJwtDemoKey2026-WithAtLeast32Bytes"
  ADMIN_PASSWORD: "PlayHub123"
